const faqData = [
    { question: "What is SkillVeda?", answer: "SkillVeda is a leading upskilling and training platform that offers courses in technology, business, and soft skills to help individuals advance their careers." },
    { question: "What courses do you offer?", answer: "SkillVeda offers courses in AI, Data Science, Web Development, Digital Marketing, Cybersecurity, UI/UX, Leadership, and more." },
    { question: "Do you provide certifications?", answer: "Yes! SkillVeda provides industry-recognized certifications upon course completion to boost your resume." },
    { question: "Who are the instructors?", answer: "Our instructors are industry experts with years of experience in their respective fields." },
    { question: "Can I access courses at my own pace?", answer: "Yes! SkillVeda offers self-paced learning, allowing you to complete courses anytime, anywhere." },
    { question: "What is the refund policy?", answer: "We offer a 7-day refund policy if you are unsatisfied with a course." },
    { question: "Tell me about your internship programs.", answer: "SkillVeda provides internship opportunities in IT, Business, AI, and Digital Marketing, offering real-world experience." },
    { question: "What is the SkillVeda Summer Training Program?", answer: "Our Summer Training Program offers hands-on training in AI, Data Science, Cybersecurity, and more, taught by industry experts." },
    { question: "Do you provide placement support?", answer: "Yes, we assist students in securing job placements by offering career guidance and networking opportunities." },
    { question: "How do I contact SkillVeda support?", answer: "You can contact SkillVeda support through the 'Help & Support' section on our website or via email." },
    { question: "Where is SkillVeda located?", answer: "SkillVeda is headquartered in Noida and operates across India, catering to students and professionals nationwide." },
    { question: "How do I reset my password?", answer: "Go to your profile settings and click 'Reset Password'. Follow the instructions sent to your email." },
    { question: "Where can I find my enrolled courses?", answer: "You can find your enrolled courses in the 'My Courses' section on your dashboard." },
    { question: "How do I contact support?", answer: "You can reach out to our support team via the 'Help & Support' section in your dashboard." },
    { question: "Can I download course materials?", answer: "Some courses allow downloads. Check the course page for downloadable resources." },
    { question: "Is there a mobile app for Skill Veda?", answer: "Currently, Skill Veda is accessible via web browsers. A mobile app is under development." },
    { question: "What payment methods are accepted?", answer: "We accept credit/debit cards, PayPal, and other major payment gateways." },
    { question: "Do you offer refunds?", answer: "Yes, we offer refunds within 7 days of purchase if you are unsatisfied with the course." },
    { question: "How do I track my progress?", answer: "Your progress is automatically saved and displayed on the course page." },
    { question: "Can I access courses offline?", answer: "Currently, courses are only available online. Offline access is planned for future updates." },
    { question: "What happens if my subscription expires?", answer: "You will lose access to premium courses until you renew your subscription." },
    { question: "How can I become an instructor?", answer: "You can apply to become an instructor from the 'Teach with Us' section on our website." },
    { question: "Is there a certificate after course completion?", answer: "Yes! You will receive a certificate after successfully completing a course." },
    { question: "How do I take quizzes?", answer: "Quizzes are available within the course modules. You can find them under 'Assessments'." },
    { question: "Can I change my username?", answer: "No, usernames cannot be changed after account creation." },
    { question: "Are there free courses available?", answer: "Yes, we offer some free courses. Check the 'Free Courses' section for details." },
    { question: "What are the system requirements to use Skill Veda?", answer: "You need a stable internet connection and a modern web browser like Chrome or Firefox." },
    { question: "How do I update my profile information?", answer: "You can update your details from the 'Profile Settings' section." },
    { question: "Can I take multiple courses at once?", answer: "Yes, you can enroll in and access multiple courses simultaneously." },
    { question: "Do courses have deadlines?", answer: "No, Skill Veda courses are self-paced, so you can complete them anytime." },
    { question: "Is there a discussion forum for students?", answer: "Yes! Each course has a discussion forum where you can ask questions and interact with others." },
    { question: "How can I apply for a discount?", answer: "Discounts are available during special promotions. Keep an eye on our website for offers." },
    { question: "Can I request a new course topic?", answer: "Yes, you can suggest new topics via the 'Course Request' form." },
    { question: "Are live sessions available?", answer: "Some courses offer live sessions. Check the course details to see if live classes are included." },
    { question: "What should I do if I forgot my login details?", answer: "Use the 'Forgot Password' option on the login page to reset your credentials." },
    { question: "How do I earn Skill Veda points?", answer: "You earn points by completing courses, quizzes, and engaging in discussions." },
    { question: "Can I change my course language?", answer: "Some courses support multiple languages. Check the settings on the course page." },
    { question: "Do you provide internship opportunities?", answer: "Yes! Completing certain courses may make you eligible for internship programs." },
    { question: "What happens if I fail a quiz?", answer: "You can retake quizzes as many times as needed to improve your score." },
    { question: "Are courses updated regularly?", answer: "Yes, our instructors update courses to ensure they remain relevant and up-to-date." },
    { question: "How do I delete my account?", answer: "You can request account deletion via the 'Account Settings' page." },
    { question: "Can I preview a course before purchasing?", answer: "Yes, many courses offer free preview videos." },
    { question: "How do I download my certificate?", answer: "After completing a course, go to the 'Certificates' section to download your certificate." },
    { question: "Do instructors provide 1-on-1 mentorship?", answer: "Some instructors offer mentorship. Check the course details for availability." },
    { question: "How do I report a technical issue?", answer: "You can report issues via the 'Help & Support' section." },
    { question: "Can I bookmark lessons?", answer: "Yes, you can bookmark lessons for quick access later." },
    { question: "Is there a referral program?", answer: "Yes! You can earn rewards by referring friends to Skill Veda." },
    { question: "Do courses include assignments?", answer: "Yes, some courses include assignments that must be completed for certification." },
    { question: "How long do I have access to purchased courses?", answer: "Purchased courses provide lifetime access unless stated otherwise." },
    { question: "Are Skill Veda courses accredited?", answer: "Our certificates are recognized, but they are not officially accredited by universities." },
    { question: "Can I ask instructors questions directly?", answer: "Yes, you can message instructors through the 'Ask Instructor' feature." },
    { question: "How do I enable subtitles for videos?", answer: "Click the 'CC' button in the video player to enable subtitles." },
    { question: "Can I switch my subscription plan?", answer: "Yes, you can upgrade or downgrade your plan from 'Subscription Settings'." },
    { question: "Does Skill Veda provide corporate training?", answer: "Yes! We offer corporate training packages. Contact our sales team for details." },
    { question: "How can I see course reviews?", answer: "Course reviews are available on the course page under the 'Reviews' section." },
    { question: "What internet speed is required for video playback?", answer: "A minimum of 5 Mbps is recommended for smooth video streaming." },
    { question: "How do I earn a Skill Veda badge?", answer: "Badges are awarded for completing specific learning milestones." },
    { question: "What file formats are supported for assignments?", answer: "We accept PDF, DOCX, and PPTX formats for assignment submissions." },
    { question: "Can I share my course progress on social media?", answer: "Yes! You can share achievements directly from your profile." },
    { question: "Are study materials available for download?", answer: "Some courses provide downloadable study materials. Check the course details." },
    { question: "Can I change my registered email?", answer: "Yes, you can update your email in 'Account Settings'." },
    { question: "What is the Skill Veda refund policy?", answer: "Refunds are available within 7 days of purchase under our refund policy." },
    { question: "Can I see how many hours a course takes?", answer: "Yes, each course page shows the estimated time required to complete it." },
    { question: "How can I learn new skills on SkillVeda?", answer: "You can browse our extensive courses, enroll, and start learning at your own pace." },
    { question: "Can I learn programming on SkillVeda?", answer: "Yes! We offer courses in Python, JavaScript, Java, and more." },
    { question: "What is the best way to learn online?", answer: "Our structured courses, live sessions, and interactive assignments help you learn effectively." },
    { question: "Do you provide certificates for learning?", answer: "Yes, SkillVeda provides certification upon course completion." },
    { question: "Is SkillVeda free to learn?", answer: "We offer both free and paid courses. Check the details on the course page." },
    { question: "Can I get cash rewards for learning?", answer: "Yes! Some courses offer incentives and rewards for top-performing students." },
    { question: "How do I earn cashback on SkillVeda?", answer: "We have promotional cashback offers available during special events." },
    { question: "What payment methods do you accept?", answer: "We accept UPI, credit/debit cards, and wallets for payments." },
    { question: "Can I withdraw my cashback balance?", answer: "Cashback earned can be used for future course enrollments." },
    { question: "Are there financial aid options available?", answer: "Yes, we offer scholarships and discounts for eligible students." },
    { question: "How do I get discounts on courses?", answer: "We run special promotions, and students can apply discount codes at checkout." },
    { question: "Can I pay for a course in installments?", answer: "Yes, we offer installment plans for selected courses." },
    { question: "What happens if my payment fails?", answer: "If a payment fails, please retry or contact our support team." },
    { question: "Do you offer refunds?", answer: "Yes, we provide refunds within 7 days of enrollment, subject to our refund policy." },
    { question: "How do I track my learning progress?", answer: "Your dashboard displays course progress, quiz scores, and completion status." },
    { question: "Are live classes available for learning?", answer: "Yes, we offer live sessions with instructors for selected courses." },
    { question: "Can I access my courses after completion?", answer: "Yes, completed courses remain accessible for future reference." },
    { question: "Do you offer group discounts for learning?", answer: "Yes, we have special pricing for corporate and group enrollments." },
    { question: "How do I redeem a course voucher?", answer: "You can enter the voucher code during checkout to redeem your discount." },
    {
        question: "What sets SkillVeda apart from other online learning platforms?",
        answer: "SkillVeda differentiates itself through its focus on industry-relevant skills, experienced instructors, personalized learning paths, and career support.",
    },
    {
        question: "Can I switch to a different course if I'm not satisfied with my current one?",
        answer: "Yes, we offer a course change option within a specific timeframe. Contact support for assistance.",
    },
    {
        question: "Does SkillVeda offer courses in regional languages?",
        answer: "Currently, most courses are in English. However, we are exploring options to introduce courses in other languages based on demand.",
    },
    {
        question: "I'm a working professional with limited time. How can SkillVeda courses fit into my schedule?",
        answer: "SkillVeda's self-paced learning model allows you to learn at your own convenience, fitting your studies around your work commitments.",
    },
    {
        question: "What is the average salary hike students have received after completing SkillVeda courses?",
        answer: "While we don't promise a specific salary increase, many students have reported significant salary hikes and career advancements after completing our courses.",
    },
    {
        question: "Do SkillVeda certificates hold value for international job applications?",
        answer: "Our industry-recognized certifications demonstrate your skills and knowledge, which can be valuable for job applications globally.",
    },
    {
        question: "Can I interact with other learners taking the same course?",
        answer: "Yes, our course discussion forums provide a platform to connect with fellow learners, ask questions, and share insights.",
    },
    {
        question: "How often are SkillVeda courses updated to reflect the latest industry trends?",
        answer: "Our courses are regularly updated with fresh content, tools, and technologies to ensure you learn the most current skills.",
    },
    {
        question: "I'm facing technical issues accessing the course content. What should I do?",
        answer: "Our technical support team is available 24/7 to assist you. Please report the issue through the 'Help & Support' section.",
    },
    {
        question: "Does SkillVeda offer job placement guarantees?",
        answer: "While we don't guarantee job placements, our dedicated career support team provides guidance, interview preparation, and connects you with potential employers.",
    },
    {
        question: "What is the role of the SkillVeda career counselor?",
        answer: "Our career counselors provide personalized guidance, resume reviews, interview tips, and help you navigate your career path.",
    },
    {
        question: "Are there any prerequisites or eligibility criteria for enrolling in SkillVeda courses?",
        answer: "Prerequisites vary depending on the course. Check the course page for specific eligibility requirements.",
    },
    {
        question: "Can I pause a course and resume it later if needed?",
        answer: "Yes, you can pause your learning at any time and return to it when you're ready.",
    },
    {
        question: "What kind of projects and assignments can I expect in SkillVeda courses?",
        answer: "Our courses feature practical projects, case studies, and assignments designed to provide hands-on experience and reinforce learning.",
    },
    {
        question: "Does SkillVeda offer any scholarships or financial aid for students?",
        answer: "Yes, we offer scholarships and financial assistance programs to deserving candidates. Check our website for eligibility criteria.",
    },
    {
        question: "Can I access SkillVeda courses from my mobile device?",
        answer: "Yes, our platform is mobile-responsive, allowing you to learn seamlessly on your smartphone or tablet.",
    },
    {
        question: "I have a query regarding a specific course. Who should I contact?",
        answer: "You can reach out to our course advisors through the 'Contact Us' page on the website.",
    },
    {
        question: "What is the SkillVeda community like?",
        answer: "We have a vibrant and supportive learning community where students, instructors, and industry professionals connect, collaborate, and learn from each other.",
    },
    {
        question: "How secure is my personal information with SkillVeda?",
        answer: "We prioritize the security of your data and use industry-standard encryption and security measures to protect your information.",
    },
    {
        question: "What is the refund process if I decide a course isn't right for me?",
        answer: "Our refund policy is outlined on the website. Contact our support team within the stipulated timeframe to initiate a refund.",
    },
    {
        question: "What are the prerequisites for enrolling in SkillVeda's advanced data science courses?",
        answer: "Prerequisites typically include a foundational understanding of statistics and programming. Specific requirements are detailed on each course page."
    },
    {
        question: "Can I transfer credits from previous certifications to accelerate my learning path at SkillVeda?",
        answer: "Currently, SkillVeda does not accept transfer credits. However, our courses are designed to accommodate various skill levels."
    },
    {
        question: "How does SkillVeda ensure the quality and industry relevance of its curriculum?",
        answer: "Our curriculum is developed in collaboration with industry experts and is regularly updated to reflect current market trends."
    },
    {
        question: "Are there any collaborative projects with industry partners included in SkillVeda's programs?",
        answer: "Yes, many programs include projects in partnership with industry leaders to provide practical experience."
    },
    {
        question: "What is the process for applying for financial aid or scholarships at SkillVeda?",
        answer: "Details about financial aid and scholarships are available on our website. Applicants can apply during the enrollment process."
    },
    {
        question: "Does SkillVeda offer mentorship opportunities with professionals in my field of interest?",
        answer: "Yes, mentorship programs are available, connecting students with experienced professionals for guidance."
    },
    {
        question: "How does SkillVeda support students in preparing for industry-recognized certifications?",
        answer: "We offer specialized training modules and practice exams aligned with industry certification standards."
    },
    {
        question: "Are there any opportunities for hands-on experience or internships through SkillVeda's programs?",
        answer: "Yes, we provide internship opportunities and practical projects to enhance real-world skills."
    },
    {
        question: "What is the typical class size for live sessions, and how does SkillVeda facilitate interaction among students?",
        answer: "Class sizes are kept small to ensure personalized attention, and we use interactive platforms to encourage student engagement."
    },
    {
        question: "Can I access course materials offline, and are there any mobile applications available for learning on the go?",
        answer: "Course materials are accessible offline, and our mobile app allows learning anytime, anywhere."
    },
    {
        question: "How does SkillVeda accommodate learners with different time zones for live sessions?",
        answer: "We offer multiple session timings and recorded lectures to accommodate various time zones."
    },
    {
        question: "What are the technical requirements for participating in SkillVeda's online courses?",
        answer: "A stable internet connection and a device capable of streaming video are essential. Specific courses may have additional requirements."
    },
    {
        question: "Does SkillVeda provide career counseling or job placement assistance upon course completion?",
        answer: "Yes, we offer career counseling services and have partnerships with companies to assist with job placements."
    },
    {
        question: "Are there any alumni networks or communities that I can join after completing a course at SkillVeda?",
        answer: "Graduates are invited to join our active alumni network for ongoing support and networking opportunities."
    },
    {
        question: "How does SkillVeda handle updates to course content in rapidly evolving fields like AI and machine learning?",
        answer: "Our team continuously reviews and updates course content to align with the latest industry developments."
    },
    {
        question: "What is the policy for course withdrawals or deferrals if I'm unable to continue?",
        answer: "We understand that circumstances change. Our withdrawal and deferral policies are outlined on our website."
    },
    {
        question: "Are there any group discounts available if I enroll with colleagues or friends?",
        answer: "Group enrollment discounts are available. Please contact our support team for more details."
    },
    {
        question: "How does SkillVeda ensure the security and privacy of my personal and payment information?",
        answer: "We employ advanced security measures to protect your data and comply with all relevant privacy regulations."
    },
    {
        question: "Can I audit a course before deciding to enroll in the full program?",
        answer: "Some courses offer audit options. Check the specific course page for availability."
    },
    {
        question: "What are the assessment methods used in SkillVeda's courses to evaluate student progress?",
        answer: "Assessments include quizzes, assignments, projects, and exams to comprehensively evaluate understanding."
    },
    {
        question: "Does SkillVeda offer any courses in emerging technologies like blockchain or quantum computing?",
        answer: "Yes, we offer courses in various emerging technologies. Visit our courses page for the latest offerings."
    },
    {
        question: "How are instructors selected, and what qualifications do they have to teach at SkillVeda?",
        answer: "Instructors are chosen based on their expertise and industry experience to ensure high-quality education."
    },
    {
        question: "Are there any language options available for non-English speakers?",
        answer: "Currently, courses are primarily in English. We are working on adding more language options in the future."
    },
    {
        question: "What is the average time commitment required per week for SkillVeda's part-time programs?",
        answer: "Part-time programs typically require 10-15 hours per week, but this may vary by course."
    },
    {
        question: "Does SkillVeda offer any preparatory courses for beginners with no prior experience in the subject matter?",
        answer: "Yes, we have foundational courses designed for beginners to build necessary skills before advancing."
    },
    {
        question: "How does SkillVeda handle feedback from students regarding course content and delivery?",
        answer: "We encourage feedback and regularly update our courses based on student input to enhance learning experiences."
    },
    {
        question: "Are there any opportunities for students to publish research or projects developed during their course?",
        answer: "Students are encouraged to publish their work, and we provide platforms and guidance to showcase their projects."
    },
    {
        question: "What partnerships does SkillVeda have with corporations or other educational institutions?",
        answer: "We collaborate with various industry partners and educational institutions to enrich our programs and provide opportunities."
    },
    {
        question: "How does SkillVeda address accessibility needs for students with disabilities?",
        answer: "We are committed to inclusivity and offer accommodations to support students with disabilities."
    },
    {
        question: "Are there any continuing education credits available for professionals taking SkillVeda courses?",
        answer: "Some courses offer continuing education credits. Please refer to the course details for specific information."
    },
    {
        question: "What sets SkillVeda apart from other online learning platforms?",
        answer: "SkillVeda differentiates itself through its focus on industry-relevant skills, experienced instructors, personalized learning paths, and career support.",
    },
    {
        question: "Can I switch to a different course if I'm not satisfied with my current one?",
        answer: "Yes, we offer a course change option within a specific timeframe. Contact support for assistance.",
    },
    {
        question: "Does SkillVeda offer courses in regional languages?",
        answer: "Currently, most courses are in English. However, we are exploring options to introduce courses in other languages based on demand.",
    },
    {
        question: "I'm a working professional with limited time. How can SkillVeda courses fit into my schedule?",
        answer: "SkillVeda's self-paced learning model allows you to learn at your own convenience, fitting your studies around your work commitments.",
    },
    {
        question: "What is the average salary hike students have received after completing SkillVeda courses?",
        answer: "While we don't promise a specific salary increase, many students have reported significant salary hikes and career advancements after completing our courses.",
    },
    {
        question: "Do SkillVeda certificates hold value for international job applications?",
        answer: "Our industry-recognized certifications demonstrate your skills and knowledge, which can be valuable for job applications globally.",
    },
    {
        question: "Can I interact with other learners taking the same course?",
        answer: "Yes, our course discussion forums provide a platform to connect with fellow learners, ask questions, and share insights.",
    },
    {
        question: "How often are SkillVeda courses updated to reflect the latest industry trends?",
        answer: "Our courses are regularly updated with fresh content, tools, and technologies to ensure you learn the most current skills.",
    },
    {
        question: "I'm facing technical issues accessing the course content. What should I do?",
        answer: "Our technical support team is available 24/7 to assist you. Please report the issue through the 'Help & Support' section.",
    },
    {
        question: "Does SkillVeda offer job placement guarantees?",
        answer: "While we don't guarantee job placements, our dedicated career support team provides guidance, interview preparation, and connects you with potential employers.",
    },
    {
        question: "What is the role of the SkillVeda career counselor?",
        answer: "Our career counselors provide personalized guidance, resume reviews, interview tips, and help you navigate your career path.",
    },
    {
        question: "Are there any prerequisites or eligibility criteria for enrolling in SkillVeda courses?",
        answer: "Prerequisites vary depending on the course. Check the course page for specific eligibility requirements.",
    },
    {
        question: "Can I pause a course and resume it later if needed?",
        answer: "Yes, you can pause your learning at any time and return to it when you're ready.",
    },
    {
        question: "What kind of projects and assignments can I expect in SkillVeda courses?",
        answer: "Our courses feature practical projects, case studies, and assignments designed to provide hands-on experience and reinforce learning.",
    },
    {
        question: "Does SkillVeda offer any scholarships or financial aid for students?",
        answer: "Yes, we offer scholarships and financial assistance programs to deserving candidates. Check our website for eligibility criteria.",
    },
    {
        question: "Can I access SkillVeda courses from my mobile device?",
        answer: "Yes, our platform is mobile-responsive, allowing you to learn seamlessly on your smartphone or tablet.",
    },
    {
        question: "I have a query regarding a specific course. Who should I contact?",
        answer: "You can reach out to our course advisors through the 'Contact Us' page on the website.",
    },
    {
        question: "What is the SkillVeda community like?",
        answer: "We have a vibrant and supportive learning community where students, instructors, and industry professionals connect, collaborate, and learn from each other.",
    },
    {
        question: "How secure is my personal information with SkillVeda?",
        answer: "We prioritize the security of your data and use industry-standard encryption and security measures to protect your information.",
    },
    {
        question: "What is the refund process if I decide a course isn't right for me?",
        answer: "Our refund policy is outlined on the website. Contact our support team within the stipulated timeframe to initiate a refund.",
    },
    { question: "What is SkillVeda?", answer: "SkillVeda is a leading upskilling and training platform that offers courses in technology, business, and soft skills to help individuals advance their careers." },
    { question: "What courses do you offer?", answer: "SkillVeda offers courses in AI, Data Science, Web Development, Digital Marketing, Cybersecurity, UI/UX, Leadership, and more." },
    { question: "Do you provide certifications?", answer: "Yes! SkillVeda provides industry-recognized certifications upon course completion to boost your resume." },
    { question: "Who are the instructors?", answer: "Our instructors are industry experts with years of experience in their respective fields." },
    { question: "Can I access courses at my own pace?", answer: "Yes! SkillVeda offers self-paced learning, allowing you to complete courses anytime, anywhere." },
    { question: "What is the refund policy?", answer: "We offer a 7-day refund policy if you are unsatisfied with a course." },
    { question: "Tell me about your internship programs.", answer: "SkillVeda provides internship opportunities in IT, Business, AI, and Digital Marketing, offering real-world experience." },
    { question: "What is the SkillVeda Summer Training Program?", answer: "Our Summer Training Program offers hands-on training in AI, Data Science, Cybersecurity, and more, taught by industry experts." },
    { question: "Do you provide placement support?", answer: "Yes, we assist students in securing job placements by offering career guidance and networking opportunities." },
    { question: "How do I contact SkillVeda support?", answer: "You can contact SkillVeda support through the 'Help & Support' section on our website or via email." },
    { question: "Where is SkillVeda located?", answer: "SkillVeda is headquartered in Noida and operates across India, catering to students and professionals nationwide." },
    { question: "How do I reset my password?", answer: "Go to your profile settings and click 'Reset Password'. Follow the instructions sent to your email." },
    { question: "Where can I find my enrolled courses?", answer: "You can find your enrolled courses in the 'My Courses' section on your dashboard." },
    { question: "How do I contact support?", answer: "You can reach out to our support team via the 'Help & Support' section in your dashboard." },
    { question: "Can I download course materials?", answer: "Some courses allow downloads. Check the course page for downloadable resources." },
    { question: "Is there a mobile app for Skill Veda?", answer: "Currently, Skill Veda is accessible via web browsers. A mobile app is under development." },
    { question: "What payment methods are accepted?", answer: "We accept credit/debit cards, PayPal, and other major payment gateways." },
    { question: "Do you offer refunds?", answer: "Yes, we offer refunds within 7 days of purchase if you are unsatisfied with the course." },
    { question: "How do I track my progress?", answer: "Your progress is automatically saved and displayed on the course page." },
    { question: "Can I access courses offline?", answer: "Currently, courses are only available online. Offline access is planned for future updates." },
    { question: "What happens if my subscription expires?", answer: "You will lose access to premium courses until you renew your subscription." },
    { question: "How can I become an instructor?", answer: "You can apply to become an instructor from the 'Teach with Us' section on our website." },
    { question: "Is there a certificate after course completion?", answer: "Yes! You will receive a certificate after successfully completing a course." },
    { question: "How do I take quizzes?", answer: "Quizzes are available within the course modules. You can find them under 'Assessments'." },
    { question: "Can I change my username?", answer: "No, usernames cannot be changed after account creation." },
    { question: "Are there free courses available?", answer: "Yes, we offer some free courses. Check the 'Free Courses' section for details." },
    { question: "What are the system requirements to use Skill Veda?", answer: "You need a stable internet connection and a modern web browser like Chrome or Firefox." },
    { question: "How do I update my profile information?", answer: "You can update your details from the 'Profile Settings' section." },
    { question: "Can I take multiple courses at once?", answer: "Yes, you can enroll in and access multiple courses simultaneously." },
    { question: "Do courses have deadlines?", answer: "No, Skill Veda courses are self-paced, so you can complete them anytime." },
    { question: "Is there a discussion forum for students?", answer: "Yes! Each course has a discussion forum where you can ask questions and interact with others." },
    { question: "How can I apply for a discount?", answer: "Discounts are available during special promotions. Keep an eye on our website for offers." },
    { question: "Can I request a new course topic?", answer: "Yes, you can suggest new topics via the 'Course Request' form." },
    { question: "Are live sessions available?", answer: "Some courses offer live sessions. Check the course details to see if live classes are included." },
    { question: "What should I do if I forgot my login details?", answer: "Use the 'Forgot Password' option on the login page to reset your credentials." },
    { question: "How do I earn Skill Veda points?", answer: "You earn points by completing courses, quizzes, and engaging in discussions." },
    { question: "Can I change my course language?", answer: "Some courses support multiple languages. Check the settings on the course page." },
    { question: "Do you provide internship opportunities?", answer: "Yes! Completing certain courses may make you eligible for internship programs." },
    { question: "What happens if I fail a quiz?", answer: "You can retake quizzes as many times as needed to improve your score." },
    { question: "Are courses updated regularly?", answer: "Yes, our instructors update courses to ensure they remain relevant and up-to-date." },
    { question: "How do I delete my account?", answer: "You can request account deletion via the 'Account Settings' page." },
    { question: "Can I preview a course before purchasing?", answer: "Yes, many courses offer free preview videos." },
    { question: "How do I download my certificate?", answer: "After completing a course, go to the 'Certificates' section to download your certificate." },
    { question: "Do instructors provide 1-on-1 mentorship?", answer: "Some instructors offer mentorship. Check the course details for availability." },
    { question: "How do I report a technical issue?", answer: "You can report issues via the 'Help & Support' section." },
    { question: "Can I bookmark lessons?", answer: "Yes, you can bookmark lessons for quick access later." },
    { question: "Is there a referral program?", answer: "Yes! You can earn rewards by referring friends to Skill Veda." },
    { question: "Do courses include assignments?", answer: "Yes, some courses include assignments that must be completed for certification." },
    { question: "How long do I have access to purchased courses?", answer: "Purchased courses provide lifetime access unless stated otherwise." },
    { question: "Are Skill Veda courses accredited?", answer: "Our certificates are recognized, but they are not officially accredited by universities." },
    { question: "Can I ask instructors questions directly?", answer: "Yes, you can message instructors through the 'Ask Instructor' feature." },
    { question: "How do I enable subtitles for videos?", answer: "Click the 'CC' button in the video player to enable subtitles." },
    { question: "Can I switch my subscription plan?", answer: "Yes, you can upgrade or downgrade your plan from 'Subscription Settings'." },
    { question: "Does Skill Veda provide corporate training?", answer: "Yes! We offer corporate training packages. Contact our sales team for details." },
    { question: "How can I see course reviews?", answer: "Course reviews are available on the course page under the 'Reviews' section." },
    { question: "What internet speed is required for video playback?", answer: "A minimum of 5 Mbps is recommended for smooth video streaming." },
    { question: "How do I earn a Skill Veda badge?", answer: "Badges are awarded for completing specific learning milestones." },
    { question: "What file formats are supported for assignments?", answer: "We accept PDF, DOCX, and PPTX formats for assignment submissions." },
    { question: "Can I share my course progress on social media?", answer: "Yes! You can share achievements directly from your profile." },
    { question: "Are study materials available for download?", answer: "Some courses provide downloadable study materials. Check the course details." },
    { question: "Can I change my registered email?", answer: "Yes, you can update your email in 'Account Settings'." },
    { question: "What is the Skill Veda refund policy?", answer: "Refunds are available within 7 days of purchase under our refund policy." },
    { question: "Can I see how many hours a course takes?", answer: "Yes, each course page shows the estimated time required to complete it." },
    { question: "How can I learn new skills on SkillVeda?", answer: "You can browse our extensive courses, enroll, and start learning at your own pace." },
    { question: "Can I learn programming on SkillVeda?", answer: "Yes! We offer courses in Python, JavaScript, Java, and more." },
    { question: "What is the best way to learn online?", answer: "Our structured courses, live sessions, and interactive assignments help you learn effectively." },
    { question: "Do you provide certificates for learning?", answer: "Yes, SkillVeda provides certification upon course completion." },
    { question: "Is SkillVeda free to learn?", answer: "We offer both free and paid courses. Check the details on the course page." },
    { question: "Can I get cash rewards for learning?", answer: "Yes! Some courses offer incentives and rewards for top-performing students." },
    { question: "How do I earn cashback on SkillVeda?", answer: "We have promotional cashback offers available during special events." },
    { question: "What payment methods do you accept?", answer: "We accept UPI, credit/debit cards, and wallets for payments." },
    { question: "Can I withdraw my cashback balance?", answer: "Cashback earned can be used for future course enrollments." },
    { question: "Are there financial aid options available?", answer: "Yes, we offer scholarships and discounts for eligible students." },
    { question: "How do I get discounts on courses?", answer: "We run special promotions, and students can apply discount codes at checkout." },
    { question: "Can I pay for a course in installments?", answer: "Yes, we offer installment plans for selected courses." },
    { question: "What happens if my payment fails?", answer: "If a payment fails, please retry or contact our support team." },
    { question: "Do you offer refunds?", answer: "Yes, we provide refunds within 7 days of enrollment, subject to our refund policy." },
    { question: "How do I track my learning progress?", answer: "Your dashboard displays course progress, quiz scores, and completion status." },
    { question: "Are live classes available for learning?", answer: "Yes, we offer live sessions with instructors for selected courses." },
    { question: "Can I access my courses after completion?", answer: "Yes, completed courses remain accessible for future reference." },
    { question: "Do you offer group discounts for learning?", answer: "Yes, we have special pricing for corporate and group enrollments." },
    { question: "How do I redeem a course voucher?", answer: "You can enter the voucher code during checkout to redeem your discount." },
    { question: "What is the difference between a course and a workshop?", answer: "Courses are comprehensive and cover a broader range of topics, while workshops are shorter and focus on specific skills." },
    { question: "Can I request a customized training program for my company?", answer: "Yes, we offer tailored corporate training solutions to meet specific organizational needs." },
    { question: "Do you offer any certifications in collaboration with industry leaders?", answer: "Yes, we partner with renowned companies to provide industry-recognized certifications." },
    { question: "What is the average course completion rate on SkillVeda?", answer: "We maintain a high course completion rate, reflecting the effectiveness of our programs." },
    { question: "Can I access SkillVeda courses from anywhere in the world?", answer: "Yes, our online platform is accessible globally, allowing you to learn from anywhere with an internet connection." },
    { question: "What is the role of a learning advisor at SkillVeda?", answer: "Learning advisors provide guidance and support to students throughout their learning journey." },
    { question: "Do you offer any career counseling services after course completion?", answer: "Yes, we provide career guidance, resume building, and interview preparation assistance to our learners." },
    { question: "Can I get a demo session before enrolling in a paid course?", answer: "Yes, many of our courses offer free preview videos or demo sessions." },
    { question: "What is the SkillVeda alumni network like?", answer: "Our alumni network provides a platform for graduates to connect, collaborate, and explore career opportunities." },
    { question: "Do you offer any job guarantee programs?", answer: "While we don't offer job guarantees, we provide extensive career support to enhance your job prospects." },
    { question: "What is the difference between a free and a paid course on SkillVeda?", answer: "Paid courses typically offer more comprehensive content, certifications, and additional benefits." },
    { question: "Can I suggest a new course topic to SkillVeda?", answer: "Yes, we welcome course suggestions from our learners. You can submit your ideas through our website." },
    { question: "How do I know if a SkillVeda course is right for me?", answer: "You can read course descriptions, reviews, and watch preview videos to determine if a course aligns with your goals." },
    { question: "What are the benefits of online learning compared to traditional classroom learning?", answer: "Online learning offers flexibility, convenience, and personalized learning experiences." },
    { question: "How do I stay updated on the latest courses and offerings from SkillVeda?", answer: "You can subscribe to our newsletter and follow us on social media for the latest updates." },
    { question: "Can I pay for SkillVeda courses using international payment methods?", answer: "Yes, we accept payments through various international payment gateways." },
    { question: "What is the process for claiming a refund for a SkillVeda course?", answer: "Our refund policy and process are detailed on our website. You can contact our support team for assistance." },
    { question: "Are there any age restrictions for enrolling in SkillVeda courses?", answer: "Most of our courses are open to learners of all ages, but some may have specific eligibility criteria." },
    { question: "Can I use SkillVeda courses to earn college credit?", answer: "While our courses provide valuable skills, they are not typically eligible for college credit." },
    { question: "What is the SkillVeda Code of Conduct?", answer: "Our Code of Conduct outlines the expected behavior and guidelines for all learners on our platform." },
    { question: "How can I provide feedback on my learning experience with SkillVeda?", answer: "We encourage learners to share their feedback through surveys, reviews, or by contacting our support team." },
    { question: "What measures does SkillVeda take to ensure the quality of its courses?", answer: "We have a rigorous course development and review process to maintain high-quality standards." },
    { question: "Can I transfer my SkillVeda course progress to another platform?", answer: "Course progress and certifications are typically specific to the SkillVeda platform." },
    { question: "What are the benefits of joining the SkillVeda affiliate program?", answer: "Our affiliate program allows you to earn commissions by promoting SkillVeda courses." },
    { question: "How can I become a SkillVeda brand ambassador?", answer: "We offer brand ambassador opportunities to passionate individuals who believe in our mission." },
    { question: "Does SkillVeda offer any scholarships or financial aid opportunities?", answer: "Yes, we provide scholarships and financial assistance programs to deserving candidates." },
    { question: "What is the SkillVeda mission?", answer: "Our mission is to empower individuals with in-demand skills to achieve their career aspirations." },
    { question: "How can I contact the SkillVeda team?", answer: "You can reach us through the 'Contact Us' page on our website, by email, or by phone." },
    { question: "Does SkillVeda offer group discounts?", answer: "Yes, we offer special pricing for corporate and group enrollments." },
    { question: "Can I get help with my assignments?", answer: "Yes, our instructors and support team are available to assist you with any questions or challenges you may have with your assignments." },
    { question: "How do I access the course materials?", answer: "Once you enroll in a course, you can access the materials through your dashboard on the SkillVeda website or mobile app." },
    { question: "Is there a time limit for completing a course?", answer: "Most of our courses are self-paced, meaning you can complete them at your own speed and convenience." },
    { question: "What happens if I don't complete a course within a certain timeframe?", answer: "You can typically access the course materials for a specified duration, even if you haven't completed the course." },
    { question: "Can I retake a course if I want to refresh my knowledge?", answer: "Yes, you can usually revisit and retake courses you've previously completed." },
    { question: "Do you offer any courses in emerging technologies?", answer: "Yes, we strive to stay up-to-date with industry trends and offer courses in areas like artificial intelligence, machine learning, and blockchain." },
    { question: "Can I download or print course certificates?", answer: "Yes, you can typically download and print your SkillVeda course certificates upon successful completion." },
    { question: "How secure are my payment details on SkillVeda?", answer: "We use industry-standard security measures to protect your payment information during transactions." },
    { question: "What is the process for updating my account information?", answer: "You can update your profile, payment details, and other account information through your account settings on the SkillVeda platform." },
    { question: "Can I use SkillVeda courses to prepare for industry certifications?", answer: "Many of our courses are designed to align with industry standards and can help you prepare for relevant certifications." },
    { question: "Do you offer any courses specifically for students?", answer: "Yes, we have courses tailored to students looking to enhance their skills and knowledge." },
    { question: "How can I contact SkillVeda support if I face technical difficulties?", answer: "You can reach our support team through the 'Help & Support' section on our website or mobile app." },
    { question: "What is the SkillVeda cancellation and refund policy?", answer: "Our cancellation and refund policy is available on our website and outlines the terms and conditions for course withdrawals and refunds." },
    { question: "Are there any discounts available for bulk purchases or corporate enrollments?", answer: "Yes, we offer special pricing and discounts for bulk purchases and corporate training programs." },
    { question: "How do I know if a SkillVeda course is recognized by employers?", answer: "Our courses are designed to equip learners with in-demand skills that are valued by employers." },
    { question: "Can I pay for SkillVeda courses using EMI options?", answer: "Yes, we offer EMI (Equated Monthly Installment) options for selected courses." },
    { question: "What is the role of mentors in SkillVeda courses?", answer: "Mentors provide guidance, support, and industry insights to learners throughout their course journey." },
    { question: "Are there any prerequisites for enrolling in SkillVeda courses?", answer: "Prerequisites vary depending on the course. Check the course page for specific eligibility criteria." },
    { question: "Can I access SkillVeda courses on my smart TV?", answer: "Our platform is optimized for web browsers and mobile devices, but accessibility on smart TVs may vary." },
    { question: "Do you offer any free resources or webinars?", answer: "Yes, we provide free resources like blog articles, webinars, and e-books on various topics." },
    { question: "How can I stay motivated while taking online courses?", answer: "Set realistic goals, create a study schedule, and engage with the course community to stay motivated." },
    { question: "What are the benefits of obtaining a SkillVeda certification?", answer: "Certifications validate your skills, enhance your resume, and can increase your earning potential." },
    { question: "Can I share my SkillVeda course certificate on social media?", answer: "Yes, you can share your achievements and certifications on social media platforms." },
    { question: "How can I provide feedback or suggestions to SkillVeda?", answer: "We value your feedback! You can share your thoughts and suggestions through our website or by contacting our support team." },
    { question: "Does SkillVeda offer personalized learning recommendations?", answer: "Yes, our platform analyzes your interests and goals to suggest relevant courses." },
    { question: "What is the typical duration of a SkillVeda course?", answer: "Course durations vary, but most can be completed in a few weeks to a few months." },
    { question: "Can I download course lectures for offline viewing?", answer: "Currently, offline viewing is not supported, but we are exploring this feature." },
    { question: "Do SkillVeda courses include any hands-on projects or assignments?", answer: "Yes, most courses incorporate practical projects to reinforce learning." },
    { question: "What is SkillVeda's stance on plagiarism in course assignments?", answer: "We have a strict policy against plagiarism. All submissions are checked for originality." },
    { question: "Can I access SkillVeda courses on my Apple TV or Roku device?", answer: "Our platform is optimized for web browsers and mobile devices, but not yet for smart TVs." },
    { question: "Does SkillVeda offer a student discount program?", answer: "Yes, we offer special discounts for eligible students. Check our website for details." },
    { question: "I'm facing difficulties enrolling in a course. What should I do?", answer: "Please contact our support team. They'll be happy to assist you with the enrollment process." },
    { question: "Does SkillVeda offer any courses in game development or animation?", answer: "Yes, we offer courses in game design, development, and related fields. Check our course catalog for more information." },
    { question: "Can I receive a refund if I cancel my course subscription before it ends?", answer: "Our refund policy varies depending on the course and subscription type. Please refer to our website or contact support for specific details." },
    { question: "What is the average instructor rating on SkillVeda?", answer: "Our instructors are highly rated by students. You can view individual instructor ratings on their profile pages." },
    { question: "Does SkillVeda offer any courses in creative writing or content marketing?", answer: "Yes, we have courses covering various aspects of writing, content creation, and digital marketing." },
    { question: "Can I connect my SkillVeda account to my LinkedIn profile?", answer: "Yes, you can integrate your SkillVeda profile with LinkedIn to showcase your skills and certifications." },
    { question: "What is SkillVeda's commitment to data privacy and security?", answer: "We prioritize the privacy and security of your data. Our platform adheres to industry-standard security measures." },
    { question: "Does SkillVeda offer any courses in foreign languages?", answer: "Yes, we offer language learning courses in various languages. Check our course offerings for the latest options." },
    { question: "Can I switch my course instructor if I'm not satisfied with their teaching style?", answer: "While instructor switching is not always feasible, you can contact support to discuss your concerns and explore possible solutions." },
    { question: "Does SkillVeda offer any mentorship programs or opportunities to connect with industry professionals?", answer: "Yes, we have mentorship programs and networking events where you can connect with mentors and industry experts." },
    { question: "What is the process for reporting technical issues or bugs on the SkillVeda platform?", answer: "You can report technical issues through the 'Help & Support' section on our website or by contacting our support team." },
    { question: "Does SkillVeda offer any group discounts for companies or organizations?", answer: "Yes, we offer corporate training packages and group discounts. Contact our sales team for more information." },
    { question: "Can I pause my SkillVeda course if I need to take a break from learning?", answer: "Yes, you can typically pause your learning and resume later. However, some courses may have specific deadlines or restrictions." },
    { question: "Does SkillVeda offer any job placement assistance to its graduates?", answer: "While we don't guarantee job placements, our career services team provides guidance, resume reviews, and connects you with potential employers." },
    { question: "Who made you?", answer: "I was created by a talented team of engineers and data scientists at Google AI." },
    { question: "Hello", answer: "Hi! 👋 What can I do for you?" },
    { question: "What is an LMS, and how does SkillVeda use it?", answer: "LMS stands for Learning Management System. It's a platform like SkillVeda that hosts online courses, tracks your progress, and lets you interact with instructors and other learners." },
    { question: "Is SkillVeda a free LMS?", answer: "SkillVeda offers both free and paid courses. You can explore our course catalog to see pricing details." },
    { question: "How do I access the SkillVeda LMS?", answer: "You can access SkillVeda through our website on your computer or mobile device. We're also developing a mobile app for even easier access." },
    { question: "Can I try SkillVeda courses before paying?", answer: "Yes, many courses offer free previews or introductory modules so you can experience the LMS and content." },
    { question: "What are the benefits of using an LMS like SkillVeda?", answer: "An LMS provides structured learning, tracks your progress, offers interactive elements, and often grants certifications upon completion." },
    { question: "How secure is my data on the SkillVeda LMS?", answer: "SkillVeda prioritizes data security and uses industry-standard encryption and protection measures." },
    { question: "Can I interact with instructors on the SkillVeda LMS?", answer: "Yes, you can typically ask questions through Q&A forums, direct messaging (if available), or live sessions." },
    { question: "What happens if I have technical issues with the SkillVeda LMS?", answer: "SkillVeda has a dedicated support team to assist you with technical difficulties. You can usually find contact details within the LMS." },
    { question: "Can I access the SkillVeda LMS on my phone?", answer: "Yes, SkillVeda is designed to be mobile-responsive. You can learn on your smartphone or tablet." },
    { question: "Does SkillVeda offer certificates upon course completion?", answer: "Yes, most SkillVeda courses provide certificates that you can add to your resume or LinkedIn profile." },
];

module.exports = faqData;